apiVersion: v1
kind: Pod
metadata:
  name: hostpath-volume-pod
spec:
  containers:
  - name: hostpath-container
    image: cr.souche-inc.com/fw/fortune
    volumeMounts:
    - name: logs
      mountPath: /var/htdocs
    ports:
    - containerPort: 8080
      protocol: TCP
  volumes:
    - name: logs
      hostPath: 
        path: /home/souche/fw/hostpath_log
        type: DirectoryOrCreate  
